# Generated by Django 6.0.7 on 2026-07-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_voting_open'),
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecriterion',
            name='category',
        ),
        migrations.AddField(
            model_name='judge',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='judge',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='judge',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='judge',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scorecriterion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='score_criteria', to='core.category'),
        ),
    ]
