import type { Project, VoterState } from "../utils/dataTypes";

export const DUMMY_PROJECTS: Project[] = [
  {
    id: "proj-1",
    registration_code: "NSE26-0001",
    title: "UniPass — NFC Smart Campus Attendance & Pass",
    tagline: "Instant contactless attendance & event entry system for NSUK students",
    description:
      "UniPass replaces manual attendance registers with secure NFC-token validation and biometric verification. Designed specifically for university departmental events and lecture halls with zero internet latency offline sync.",
    thumbnail_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    live_preview_url: "https://unipass-demo.vercel.app",
    category_id: "software-dev",
    category_name: "Software Development",
    track: "software",
    team_name: "ByteForge Studios",
    team_members: [
      { name: "Emmanuel Azimeh", role: "Fullstack Engineer", github: "https://github.com" },
      { name: "Chidiebere Okafor", role: "DevOps & Backend" },
      { name: "Blessing Audu", role: "UI/UX Lead" },
    ],
    contact_name: "Emmanuel Azimeh",
    contact_email: "e.azimeh@nsuk.edu.ng",
    contact_phone: "+234 812 345 6789",
    show_contact_publicly: true,
    registration_status: "confirmed",
    vote_count: 342,
    created_at: "2026-07-20T10:00:00Z",
    featured: true,
    tags: ["React", "Django", "NFC", "TypeScript"],
  },
  {
    id: "proj-2",
    registration_code: "NSE26-0002",
    title: "PixelCraft — NACOS Brand System & Identity",
    tagline: "Complete 3D visual language, poster system & event merchandise guidelines",
    description:
      "A comprehensive design system for NACOS NSUK Chapter. Features custom typography rules, high-contrast dark visual cards, 3D emblem renders, and print-ready exhibition banners.",
    thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    live_preview_url: "https://figma.com/@pixelcraft",
    category_id: "graphic-design",
    category_name: "Graphic & UI/UX Design",
    track: "graphic_design",
    team_name: "Aesthetic Studio",
    team_members: [
      { name: "Kemi Adeleke", role: "Brand Designer" },
      { name: "David John", role: "3D Artist" },
    ],
    contact_name: "Kemi Adeleke",
    contact_email: "kemi.adeleke@gmail.com",
    contact_phone: "+234 803 987 6543",
    show_contact_publicly: true,
    registration_status: "confirmed",
    vote_count: 289,
    created_at: "2026-07-20T11:30:00Z",
    featured: true,
    tags: ["Figma", "Blender", "Branding", "UI/UX"],
  },
  {
    id: "proj-3",
    registration_code: "NSE26-0003",
    title: "EduPulse AI — Smart Course Tutor & Assistant",
    tagline: "AI study companion trained on NSUK Computer Science syllabus",
    description:
      "EduPulse leverages local LLM fine-tuning to deliver tailored instant answers to complex CS topics, past question solutions, and automated code review for students.",
    thumbnail_url: "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80",
    live_preview_url: "https://edupulse-ai.dev",
    category_id: "ai-data",
    category_name: "AI & Machine Learning",
    track: "software",
    team_name: "Neural Tribe",
    team_members: [
      { name: "Usman Ibrahim", role: "AI Engineer" },
      { name: "Grace Danjuma", role: "Frontend Dev" },
    ],
    contact_name: "Usman Ibrahim",
    contact_email: "usman.ibrahim@nsuk.edu.ng",
    contact_phone: "+234 901 234 5678",
    show_contact_publicly: false,
    registration_status: "confirmed",
    vote_count: 215,
    created_at: "2026-07-20T14:15:00Z",
    featured: false,
    tags: ["Python", "FastAPI", "Gemini", "Tailwind"],
  },
  {
    id: "proj-4",
    registration_code: "NSE26-0004",
    title: "PhishShield — Browser Anti-Phishing Extension",
    tagline: "Real-time AI domain verification & spoof detection for student portals",
    description:
      "Protects university students from credential phishing attacks targeting student portals. Evaluates SSL certificates, domain age, and page structure heuristics in real-time.",
    thumbnail_url: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
    live_preview_url: "https://phishshield.security",
    category_id: "cybersecurity",
    category_name: "Cybersecurity & Tools",
    track: "software",
    team_name: "CyberSec Alpha",
    team_members: [
      { name: "Samuel Yakubu", role: "Security Researcher" },
      { name: "Fatima Aliyu", role: "Extension Dev" },
    ],
    contact_name: "Samuel Yakubu",
    contact_email: "samuel.yakubu@nsuk.edu.ng",
    contact_phone: "+234 814 111 2222",
    show_contact_publicly: true,
    registration_status: "confirmed",
    vote_count: 178,
    created_at: "2026-07-21T09:00:00Z",
    featured: false,
    tags: ["Cybersecurity", "Chrome API", "Rust", "TypeScript"],
  },
  {
    id: "proj-5",
    registration_code: "NSE26-0005",
    title: "CampusRide — Peer-to-Peer Campus Logistics",
    tagline: "Shared shuttle and package delivery web app for NSUK Keffi campus",
    description:
      "Connects student drivers with peers needing campus mobility or errand delivery. Features real-time GPS tracking, fare splitting, and matric-verified trust scores.",
    thumbnail_url: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
    live_preview_url: "https://campusride.ng",
    category_id: "software-dev",
    category_name: "Software Development",
    track: "software",
    team_name: "Velocity Devs",
    team_members: [
      { name: "Tunde Bakare", role: "Mobile Lead" },
      { name: "Ngozi Eze", role: "Backend Developer" },
    ],
    contact_name: "Tunde Bakare",
    contact_email: "tunde.bakare@nsuk.edu.ng",
    contact_phone: "+234 805 444 3333",
    show_contact_publicly: true,
    registration_status: "confirmed",
    vote_count: 142,
    created_at: "2026-07-21T11:45:00Z",
    featured: false,
    tags: ["React Native", "Firebase", "Node.js"],
  },
  {
    id: "proj-6",
    registration_code: "NSE26-0006",
    title: "Echo UI — Accessible Dark Theme System",
    tagline: "WCAG AAA accessible UI design system & poster series for developer tools",
    description:
      "A high-contrast visual component library and design layout crafted specifically for developers with low vision or photophobia. Includes dark mode guidelines and palette tools.",
    thumbnail_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    category_id: "graphic-design",
    category_name: "Graphic & UI/UX Design",
    track: "graphic_design",
    team_name: "Contrast Lab",
    team_members: [{ name: "Zainab Bello", role: "Lead Designer" }],
    contact_name: "Zainab Bello",
    contact_email: "zainab.bello@design.io",
    contact_phone: "+234 703 888 9999",
    show_contact_publicly: true,
    registration_status: "confirmed",
    vote_count: 118,
    created_at: "2026-07-21T13:20:00Z",
    featured: false,
    tags: ["Figma", "Accessibility", "Design Systems"],
  },
];

export const INITIAL_VOTER_STATE: VoterState = {
  matricNumber: null,
  isVerified: false,
  votedCategoryIds: [],
};
