/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HomeRouteImport } from './routes/home'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeJudgeRouteImport } from './routes/home/judge'
import { Route as HomeJudgeLoginRouteImport } from './routes/home/judge-login'
import { Route as HomeJudgeScoreRouteImport } from './routes/home/judge/score'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeJudgeRoute = HomeJudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => HomeRoute,
} as any)
const HomeJudgeLoginRoute = HomeJudgeLoginRouteImport.update({
  id: '/judge-login',
  path: '/judge-login',
  getParentRoute: () => HomeRoute,
} as any)
const HomeJudgeScoreRoute = HomeJudgeScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => HomeJudgeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRouteWithChildren
  '/register': typeof RegisterRoute
  '/home/judge': typeof HomeJudgeRouteWithChildren
  '/home/judge-login': typeof HomeJudgeLoginRoute
  '/home/': typeof HomeIndexRoute
  '/home/judge/score': typeof HomeJudgeScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/register': typeof RegisterRoute
  '/home/judge': typeof HomeJudgeRouteWithChildren
  '/home/judge-login': typeof HomeJudgeLoginRoute
  '/home': typeof HomeIndexRoute
  '/home/judge/score': typeof HomeJudgeScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRouteWithChildren
  '/register': typeof RegisterRoute
  '/home/judge': typeof HomeJudgeRouteWithChildren
  '/home/judge-login': typeof HomeJudgeLoginRoute
  '/home/': typeof HomeIndexRoute
  '/home/judge/score': typeof HomeJudgeScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/home'
    | '/register'
    | '/home/judge'
    | '/home/judge-login'
    | '/home/'
    | '/home/judge/score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/register'
    | '/home/judge'
    | '/home/judge-login'
    | '/home'
    | '/home/judge/score'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/home'
    | '/register'
    | '/home/judge'
    | '/home/judge-login'
    | '/home/'
    | '/home/judge/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  HomeRoute: typeof HomeRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/judge': {
      id: '/home/judge'
      path: '/judge'
      fullPath: '/home/judge'
      preLoaderRoute: typeof HomeJudgeRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/judge-login': {
      id: '/home/judge-login'
      path: '/judge-login'
      fullPath: '/home/judge-login'
      preLoaderRoute: typeof HomeJudgeLoginRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/judge/score': {
      id: '/home/judge/score'
      path: '/score'
      fullPath: '/home/judge/score'
      preLoaderRoute: typeof HomeJudgeScoreRouteImport
      parentRoute: typeof HomeJudgeRoute
    }
  }
}

interface HomeJudgeRouteChildren {
  HomeJudgeScoreRoute: typeof HomeJudgeScoreRoute
}

const HomeJudgeRouteChildren: HomeJudgeRouteChildren = {
  HomeJudgeScoreRoute: HomeJudgeScoreRoute,
}

const HomeJudgeRouteWithChildren = HomeJudgeRoute._addFileChildren(
  HomeJudgeRouteChildren,
)

interface HomeRouteChildren {
  HomeJudgeRoute: typeof HomeJudgeRouteWithChildren
  HomeJudgeLoginRoute: typeof HomeJudgeLoginRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeJudgeRoute: HomeJudgeRouteWithChildren,
  HomeJudgeLoginRoute: HomeJudgeLoginRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  HomeRoute: HomeRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
