# Generated by Django 6.0.7 on 2026-07-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_description_category_icon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='track',
            field=models.CharField(choices=[('software', 'Software Track'), ('graphic_design', 'Design Track'), ('ai_prompting', 'AI Prompting')], default='software', max_length=50),
        ),
    ]
