# Generated by Django 6.0.7 on 2026-07-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='track',
            field=models.CharField(choices=[('software', 'Software Track'), ('graphic_design', 'Design Track'), ('ai_prompting', 'AI Prompting')], default='software', max_length=50),
        ),
    ]
