# Generated by Django 6.0.7 on 2026-07-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='voting_open',
            field=models.BooleanField(default=True),
        ),
    ]
