# Generated by Django 6.0.7 on 2026-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_voting_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='matric_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
