# Generated by Django 6.0.7 on 2026-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_level_project_matric_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
