# Generated by Django 6.0.7 on 2026-07-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
